package entities;
// Generated Nov 28, 2017 11:11:12 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Anomalia generated by hbm2java
 */
@Entity
@Table(name = "anomalia", catalog = "rilasci_db")
public class Anomalia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Priority priority;
	private Resolution resolution;
	private Severity severity;
	private String idPolarion;
	private String titolo;
	private Date dataCreazione;
	private Set<AnomaliaHistory> anomaliaHistories = new HashSet<AnomaliaHistory>(0);

	public Anomalia() {
	}

	public Anomalia(Priority priority, Resolution resolution, Severity severity, String idPolarion, String titolo,
			Date dataCreazione, Set<AnomaliaHistory> anomaliaHistories) {
		this.priority = priority;
		this.resolution = resolution;
		this.severity = severity;
		this.idPolarion = idPolarion;
		this.titolo = titolo;
		this.dataCreazione = dataCreazione;
		this.anomaliaHistories = anomaliaHistories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_priority")
	public Priority getPriority() {
		return this.priority;
	}

	public void setPriority(Priority priority) {
		this.priority = priority;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_resolution")
	public Resolution getResolution() {
		return this.resolution;
	}

	public void setResolution(Resolution resolution) {
		this.resolution = resolution;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_severity")
	public Severity getSeverity() {
		return this.severity;
	}

	public void setSeverity(Severity severity) {
		this.severity = severity;
	}

	@Column(name = "id_polarion", length = 65535)
	public String getIdPolarion() {
		return this.idPolarion;
	}

	public void setIdPolarion(String idPolarion) {
		this.idPolarion = idPolarion;
	}

	@Column(name = "titolo", length = 65535)
	public String getTitolo() {
		return this.titolo;
	}

	public void setTitolo(String titolo) {
		this.titolo = titolo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_creazione", length = 19)
	public Date getDataCreazione() {
		return this.dataCreazione;
	}

	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "anomalia")
	public Set<AnomaliaHistory> getAnomaliaHistories() {
		return this.anomaliaHistories;
	}

	public void setAnomaliaHistories(Set<AnomaliaHistory> anomaliaHistories) {
		this.anomaliaHistories = anomaliaHistories;
	}

}
