package entities;
// Generated Nov 28, 2017 11:11:12 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Assignee generated by hbm2java
 */
@Entity
@Table(name = "assignee", catalog = "rilasci_db")
public class Assignee implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private AssigneeId id;
	private Mev releaseIt;
	private User user;
	private Integer codTipo;

	public Assignee() {
	}

	public Assignee(AssigneeId id, User user) {
		this.id = id;
		this.user = user;
	}

	public Assignee(AssigneeId id, Mev releaseIt, User user, Integer codTipo) {
		this.id = id;
		this.releaseIt = releaseIt;
		this.user = user;
		this.codTipo = codTipo;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codIdUser", column = @Column(name = "cod_id_user", nullable = false)),
			@AttributeOverride(name = "codIdPolarion", column = @Column(name = "cod_id_polarion", nullable = false, length = 45)) })
	public AssigneeId getId() {
		return this.id;
	}

	public void setId(AssigneeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_id")
	public Mev getReleaseIt() {
		return this.releaseIt;
	}

	public void setReleaseIt(Mev releaseIt) {
		this.releaseIt = releaseIt;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_id_user", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "cod_tipo")
	public Integer getCodTipo() {
		return this.codTipo;
	}

	public void setCodTipo(Integer codTipo) {
		this.codTipo = codTipo;
	}

}
