package entities;
// Generated Nov 28, 2017 11:11:12 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AssigneeId generated by hbm2java
 */
@Embeddable
public class AssigneeId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int codIdUser;
	private String codIdPolarion;

	public AssigneeId() {
	}

	public AssigneeId(int codIdUser, String codIdPolarion) {
		this.codIdUser = codIdUser;
		this.codIdPolarion = codIdPolarion;
	}

	@Column(name = "cod_id_user", nullable = false)
	public int getCodIdUser() {
		return this.codIdUser;
	}

	public void setCodIdUser(int codIdUser) {
		this.codIdUser = codIdUser;
	}

	@Column(name = "cod_id_polarion", nullable = false, length = 45)
	public String getCodIdPolarion() {
		return this.codIdPolarion;
	}

	public void setCodIdPolarion(String codIdPolarion) {
		this.codIdPolarion = codIdPolarion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AssigneeId))
			return false;
		AssigneeId castOther = (AssigneeId) other;

		return (this.getCodIdUser() == castOther.getCodIdUser())
				&& ((this.getCodIdPolarion() == castOther.getCodIdPolarion())
						|| (this.getCodIdPolarion() != null && castOther.getCodIdPolarion() != null
								&& this.getCodIdPolarion().equals(castOther.getCodIdPolarion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodIdUser();
		result = 37 * result + (getCodIdPolarion() == null ? 0 : this.getCodIdPolarion().hashCode());
		return result;
	}

}
