package entities;
// Generated Nov 28, 2017 11:11:12 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Checklist generated by hbm2java
 */
@Entity
@Table(name = "checklist", catalog = "rilasci_db")
public class Checklist implements java.io.Serializable {

	private Integer id;
	private String idPolarion;
	private Date dataCreazione;
	private Date dataFine;
	private Date dataUpdate;
	private Set<ChecklistTestcase> checklistTestcases = new HashSet<ChecklistTestcase>(0);
	private Status status;
	private Status esitoChecklist;
	
	public Checklist() {
	}

	public Checklist(String idPolarion, Date dataCreazione, Date dataFine, Date dataUpdate,
			Set<ChecklistTestcase> checklistTestcases) {
		this.idPolarion = idPolarion;
		this.dataCreazione = dataCreazione;
		this.dataFine = dataFine;
		this.dataUpdate = dataUpdate;
		this.checklistTestcases = checklistTestcases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "id_polarion", length = 45)
	public String getIdPolarion() {
		return this.idPolarion;
	}

	public void setIdPolarion(String idPolarion) {
		this.idPolarion = idPolarion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_creazione", length = 19)
	public Date getDataCreazione() {
		return this.dataCreazione;
	}

	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_fine", length = 19)
	public Date getDataFine() {
		return this.dataFine;
	}

	public void setDataFine(Date dataFine) {
		this.dataFine = dataFine;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_update", length = 19)
	public Date getDataUpdate() {
		return this.dataUpdate;
	}

	public void setDataUpdate(Date dataUpdate) {
		this.dataUpdate = dataUpdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "checklist")
	public Set<ChecklistTestcase> getChecklistTestcases() {
		return this.checklistTestcases;
	}

	public void setChecklistTestcases(Set<ChecklistTestcase> checklistTestcases) {
		this.checklistTestcases = checklistTestcases;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_status")
	public Status getStatus() {
		return status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "esito_checklist")
	public Status getEsitoChecklist() {
		return esitoChecklist;
	}

	public void setEsitoChecklist(Status esitoChecklist) {
		this.esitoChecklist = esitoChecklist;
	}

}
