package entities;
// Generated Nov 28, 2017 11:11:12 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LinkedItem generated by hbm2java
 */
@Entity
@Table(name = "linked_item", catalog = "rilasci_db")
public class LinkedItem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private LinkedItemId id;
	private TipoRole tipoRole;

	public LinkedItem() {
	}

	public LinkedItem(LinkedItemId id) {
		this.id = id;
	}

	public LinkedItem(LinkedItemId id, TipoRole tipoRole) {
		this.id = id;
		this.tipoRole = tipoRole;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idPolarionPadre", column = @Column(name = "id_polarion_padre", nullable = false, length = 45)),
			@AttributeOverride(name = "idPolarionFiglio", column = @Column(name = "id_polarion_figlio", nullable = false, length = 45)) })
	public LinkedItemId getId() {
		return this.id;
	}

	public void setId(LinkedItemId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_tipo_role")
	public TipoRole getTipoRole() {
		return this.tipoRole;
	}

	public void setTipoRole(TipoRole tipoRole) {
		this.tipoRole = tipoRole;
	}

}
