package entities;
// Generated Nov 28, 2017 11:11:12 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Taskit generated by hbm2java
 */
@Entity
@Table(name = "taskit", catalog = "rilasci_db")
public class Taskit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Priority priority;
	private Resolution resolution;
	private TipoItem tipoItem;
	private User user;
	private String idPolarion;
	private String titolo;
	private Date dataCreazione;
	private Date dataInizio;
	private Date dataFine;
	private String timespent;
	private String initialEstimate;
	private Set<TaskitWorkitem> taskitWorkitems = new HashSet<TaskitWorkitem>(0);
	private Set<TaskItHistory> taskItHistories = new HashSet<TaskItHistory>(0);

	public Taskit() {
	}

	public Taskit(Priority priority, Resolution resolution, TipoItem tipoItem, User user, String idPolarion,
			String titolo, Date dataCreazione, Date dataInizio, Date dataFine, String timespent, String initialEstimate,
			Set<TaskitWorkitem> taskitWorkitems, Set<TaskItHistory> taskItHistories) {
		this.priority = priority;
		this.resolution = resolution;
		this.tipoItem = tipoItem;
		this.user = user;
		this.idPolarion = idPolarion;
		this.titolo = titolo;
		this.dataCreazione = dataCreazione;
		this.dataInizio = dataInizio;
		this.dataFine = dataFine;
		this.timespent = timespent;
		this.initialEstimate = initialEstimate;
		this.taskitWorkitems = taskitWorkitems;
		this.taskItHistories = taskItHistories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_priority")
	public Priority getPriority() {
		return this.priority;
	}

	public void setPriority(Priority priority) {
		this.priority = priority;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_resolution")
	public Resolution getResolution() {
		return this.resolution;
	}

	public void setResolution(Resolution resolution) {
		this.resolution = resolution;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_tipo")
	public TipoItem getTipoItem() {
		return this.tipoItem;
	}

	public void setTipoItem(TipoItem tipoItem) {
		this.tipoItem = tipoItem;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_author")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "id_polarion", length = 255)
	public String getIdPolarion() {
		return this.idPolarion;
	}

	public void setIdPolarion(String idPolarion) {
		this.idPolarion = idPolarion;
	}

	@Column(name = "titolo", length = 65535)
	public String getTitolo() {
		return this.titolo;
	}

	public void setTitolo(String titolo) {
		this.titolo = titolo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_creazione", length = 19)
	public Date getDataCreazione() {
		return this.dataCreazione;
	}

	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_inizio", length = 19)
	public Date getDataInizio() {
		return this.dataInizio;
	}

	public void setDataInizio(Date dataInizio) {
		this.dataInizio = dataInizio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_fine", length = 19)
	public Date getDataFine() {
		return this.dataFine;
	}

	public void setDataFine(Date dataFine) {
		this.dataFine = dataFine;
	}

	@Column(name = "timespent", length = 200)
	public String getTimespent() {
		return this.timespent;
	}

	public void setTimespent(String timespent) {
		this.timespent = timespent;
	}

	@Column(name = "initialEstimate", length = 10)
	public String getInitialEstimate() {
		return this.initialEstimate;
	}

	public void setInitialEstimate(String initialEstimate) {
		this.initialEstimate = initialEstimate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taskit")
	public Set<TaskitWorkitem> getTaskitWorkitems() {
		return this.taskitWorkitems;
	}

	public void setTaskitWorkitems(Set<TaskitWorkitem> taskitWorkitems) {
		this.taskitWorkitems = taskitWorkitems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taskit")
	public Set<TaskItHistory> getTaskItHistories() {
		return this.taskItHistories;
	}

	public void setTaskItHistories(Set<TaskItHistory> taskItHistories) {
		this.taskItHistories = taskItHistories;
	}

}
