package entities;
// Generated Nov 28, 2017 11:11:12 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoItem generated by hbm2java
 */
@Entity
@Table(name = "tipo_item", catalog = "rilasci_db")
public class TipoItem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String nome;
	private Set<Documento> documentos = new HashSet<Documento>(0);
	private Set<Taskit> taskits = new HashSet<Taskit>(0);

	public TipoItem() {
	}

	public TipoItem(String nome, Set<Documento> documentos, Set<Taskit> taskits) {
		this.nome = nome;
		this.documentos = documentos;
		this.taskits = taskits;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoItem")
	public Set<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<Documento> documentos) {
		this.documentos = documentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoItem")
	public Set<Taskit> getTaskits() {
		return this.taskits;
	}

	public void setTaskits(Set<Taskit> taskits) {
		this.taskits = taskits;
	}

}
