package entities;
// Generated Nov 28, 2017 11:11:12 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Workrecords generated by hbm2java
 */
@Entity
@Table(name = "workrecords", catalog = "rilasci_db")
public class Workrecords implements java.io.Serializable {

	private Integer id;
	private User user;
	private String typeLink;
	private String idPolarion;
	private Date dateUpdate;
	private String workTime;
	private String workType;
	private String note;

	public Workrecords() {
	}

	public Workrecords(User user, String typeLink, String idPolarion, Date dateUpdate, String workTime, String workType,
			String note) {
		this.user = user;
		this.typeLink = typeLink;
		this.idPolarion = idPolarion;
		this.dateUpdate = dateUpdate;
		this.workTime = workTime;
		this.workType = workType;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_author")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "type_link", length = 10)
	public String getTypeLink() {
		return this.typeLink;
	}

	public void setTypeLink(String typeLink) {
		this.typeLink = typeLink;
	}

	@Column(name = "id_polarion", length = 45)
	public String getIdPolarion() {
		return this.idPolarion;
	}

	public void setIdPolarion(String idPolarion) {
		this.idPolarion = idPolarion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_update", length = 19)
	public Date getDateUpdate() {
		return this.dateUpdate;
	}

	public void setDateUpdate(Date dateUpdate) {
		this.dateUpdate = dateUpdate;
	}

	@Column(name = "work_time", length = 25)
	public String getWorkTime() {
		return this.workTime;
	}

	public void setWorkTime(String workTime) {
		this.workTime = workTime;
	}

	@Column(name = "work_type", length = 45)
	public String getWorkType() {
		return this.workType;
	}

	public void setWorkType(String workType) {
		this.workType = workType;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
